### ISSUE TITLE
build with LibreSSL 2.7.0/2.7.1 fails

### ISSUE THREAD

**Issue by woohooyeah** [irssi/irssi#864]
Hi,
I tried compiling irssi 1.1.1 and master (git), but both fail to build with LibreSSL 2.7.0:
```
network-openssl.c:51:12: error: static declaration of ‘X509_STORE_up_ref’ follows non-static declaration
 static int X509_STORE_up_ref(X509_STORE *vfy)
            ^
In file included from /usr/local/include/openssl/x509.h:595:0,
                 from /usr/local/include/openssl/pem.h:71,
                 from /usr/local/include/openssl/ssl.h:150,
                 from tls.h:22,
                 from network-openssl.c:28:
/usr/local/include/openssl/x509_vfy.h:435:5: note: previous declaration of ‘X509_STORE_up_ref’ was here
 int X509_STORE_up_ref(X509_STORE *x);
     ^
Makefile:564: recipe for target 'network-openssl.o' failed
make[3]: *** [network-openssl.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/home/username/build/irssi-1.1.1/src/core'
Makefile:445: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/username/build/irssi-1.1.1/src'
Makefile:543: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/username/build/irssi-1.1.1'
Makefile:423: recipe for target 'all' failed
make: *** [all] Error 2
```
I found [this](http://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/net/irssi/patches/patch-src_core_network-openssl_c?rev=1.6&content-type=text/x-cvsweb-markup) patch from the OpenBSD folks, it prevents the error.

**Comment by ailin-nemui** [comment]
please submit a PR

**Comment by woohooyeah** [comment]
Done, see [here](https://github.com/irssi/irssi/pull/865)
